# bryxcoin server configuration file

# the mongodb target to read from to fetch user addresses and secrets
mongo_connection_string = "<mongo_connection_string>"
mongo_user_database = "bryxcoin"
mongo_user_collection = "users"

# the public and private key pair to authenticate to git with
public_key = "~/.ssh/id_ed25519.pub"
private_key = "~/.ssh/id_ed25519"

# the git repo to use as the bryxcoin ledger
ledger_repo = "git@github.com:bryxcoin/ledger.git"

# the port to host the bryxcoin server on
port = 8001
